name: flutterwave_standard
description: Flutterwave's official library that wraps the standard implementation.
version: 1.0.6
homepage: https://github.com/Flutterwave/flutter_standard
environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  webview_flutter: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
